<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Models\Presensi\Jadwal;
use App\Models\Presensi\RealAbsensi;
use Illuminate\Support\Carbon;

class MarkAbsences extends Command
{
    protected $signature = 'absensi:mark-absent';
    protected $description = 'Tandai karyawan yang tidak melakukan absensi sebagai ALPA berdasarkan jadwal';

    public function handle()
    {
        $now = Carbon::now();
        $today = $now->toDateString();
        $this->info("Memeriksa jadwal yang terlewat pada: " . $now->toDateTimeString());

        // Toleransi keterlambatan sebelum dianggap ALPA (misal: 1 jam)
        $toleranceHours = 1;

        // 1. Ambil semua jadwal kerja hari ini yang jam masuknya sudah terlewat + toleransi
        $schedulesToCheck = Jadwal::where('tmp_periode', $now->format('Y-m'))
                                  ->where('emp_tgl', $now->format('d'))
                                  ->whereNotIn('shift_code', ['L', 'OFF'])
                                  ->where('jam_in', '<=', $now->copy()->subHours($toleranceHours)->toTimeString())
                                  ->get();

        if ($schedulesToCheck->isEmpty()) {
            $this->info("Tidak ada jadwal yang perlu diperiksa saat ini.");
            return;
        }
        
        // 2. Ambil ID semua karyawan yang sudah punya record absensi hari ini (apapun statusnya)
        $presentEmployeeIds = RealAbsensi::where('TS_TANGGAL', $today)
                                          ->pluck('TS_EMP')
                                          ->unique()
                                          ->toArray();
        
        $absentCount = 0;
        foreach ($schedulesToCheck as $schedule) {
            // 3. Jika karyawan terjadwal TIDAK ADA di daftar yang sudah absen, tandai ALPA
            if (!in_array($schedule->TMP_emp, $presentEmployeeIds)) {
                
                RealAbsensi::create([
                    'TS_EMP'        => $schedule->TMP_emp,
                    'TS_NAME'       => $schedule->TMP_NAME,
                    'TS_CODE'       => $schedule->TMP_CODE,
                    'TS_TANGGAL'    => $today,
                    'TS_STATUS'     => 'ALPA',
                    'TS_NOTE'       => 'Tidak Hadir (Generated by System)',
                    'TS_ENTRYDATE'  => now(),
                    'TS_ENTRYUSER'  => 'SYSTEM',
                    'TS_ACTIVE'     => 'Y',
                ]);

                // Tambahkan kembali ID-nya ke array agar tidak diproses lagi di iterasi berikutnya
                $presentEmployeeIds[] = $schedule->TMP_emp;
                $absentCount++;
                $this->warn("Karyawan: {$schedule->TMP_NAME} ditandai ALPA.");
            }
        }

        $this->info("Proses selesai. Total karyawan ditandai ALPA pada proses ini: {$absentCount}");
        return 0;
    }
}
